# SITE CONFIGURATION
baseurl: "/portfolio"
url: "https://smillerworks.github.io/"

# THEME-SPECIFIC CONFIGURATION
title: Sarah Miller                                   # site's title
description: "My game development portfolio representing four years of work"      # used by search engines
avatar: assets/img/suggs_icon_round.png                 # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: My Portfolio  # Change Blog header text
header_feature_image: assets/img/black&yellowshapes.jpg     
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>
  <br>
  <b>smillerworks@protonmail.com</b>
  <br>
  <b>(xxx) xxx-xxxx</b>

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
